apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - namespace.yaml
  - longhorn-ingress.yaml
  - longhorn-frontend-certificate.yaml
  - secret.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: v1.8.0
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: longhorn-values.yaml
