apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-frontend-tls
  namespace: longhorn-system
spec:
  dnsNames:
    - longhorn.arffornia.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: default-issuer
  secretName: longhorn-frontend-tls