apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
spec:
  path: "secret/minio-s3/credentials"
  keys:
    - rootUser
    - rootPassword
  templates:
    AWS_ACCESS_KEY_ID: "{% .Secrets.rootUser %}"
    AWS_SECRET_ACCESS_KEY: "{% .Secrets.rootPassword %}"
  type: Opaque