minecraftServer:
  motd: "Welcome to Minecraft on Kubernetes Arcane!"

mcbackup:
  enabled: true
  
  persistence:
    backupDir:
      enabled: true
      existingClaim: "arffornia-backup-arcane-pvc"
      Size: 100Gi
      accessModes:
        - ReadWriteOnce

extraVolumes:
  - volumeMounts:
      - name: bluemap-data
        mountPath: /data/bluemap-web
    volumes:
      - name: bluemap-data
        persistentVolumeClaim:
          claimName: arffornia-bluemap-pvc
