apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arffornia-backup-arcane-pvc
  namespace: arffornia-server-arcane
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: smb-nas
  volumeName: pv-arffornia-backup-arcane