apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-secrets-operator

resources:
  - namespace.yaml
  - secret.yaml
  
helmCharts:
  - name: vault-secrets-operator
    repo: oci://ghcr.io/ricoberger/charts
    version: 3.0.0
    releaseName: vault-secrets-operator
    namespace: vault-secrets-operator
    valuesFile: vso-values.yaml
