apiVersion: v1
kind: Endpoints
metadata:
  name: ollama-external-service
  namespace: ollama
subsets:
  - addresses:
      - ip: "192.168.1.20" 
    ports:
      - name: http
        port: 11434
        protocol: TCP