routes:
  ollama:
    hostnames:
      - "ollama.arffornia.com"
    rules:
      - backendRefs:
          - name: ollama-external-service
            port: 11434
    auth:
      enabled: false
    ipFilter:
      enabled: false
