apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - namespace.yaml
  - vault-certificate.yaml
  - k8s-auth-sa.yaml
  
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.29.1
    releaseName: vault
    namespace: vault
    valuesFile: vault-values.yaml


