apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls 
  dnsNames:
    - vault.arffornia.com
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
    group: cert-manager.io
