apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage-s3

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: secure-route
    releaseName: garage-routes
    namespace: garage-s3
    valuesFile: values-secure-route.yaml
