apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator-ui
  template:
    metadata:
      labels:
        app: postgres-operator-ui
    spec:
      containers:
      - name: postgres-operator-ui
        image: zalando/postgres-operator-ui:latest
        ports:
        - containerPort: 8080
