apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-server-nexus

resources:
  - ../../base/
  - namespace.yaml
  - secret.yaml
  - service-account.yaml

patches:
  - path: patch-deployment-sa.yaml
    target:
      kind: Deployment
      name: arffornia-server-nexus-minecraft

helmCharts:
  - name: minecraft
    repo: oci://ghcr.io/itzg/minecraft-server-charts
    version: 4.26.3
    releaseName: arffornia-server-nexus
    namespace: arffornia-server-nexus
    valuesFile: ../../base/values.yaml
    additionalValuesFiles: # Shallow merge
      - patch-values.yaml
