apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-server-nexus

resources:
  - ../../base
  - namespace.yaml

helmCharts:
  - name: minecraft
    repo: ghcr.io/itzg/minecraft-server-charts
    version: 4.26.3
    releaseName: arffornia-server-nexus
    namespace: arffornia-server-nexus
    valuesFile: patch-values.yaml

