apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arffornia-bluemap-pvc  
  namespace: arffornia-server-nexus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: smb-nas
  volumeName: pv-arffornia-bluemap 