apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-db-secret
  namespace: arffornia-server-nexus

spec:
  kubernetes:
    role: arffornia-server-nexus
    authPath: kubernetes 
    
  path: secret/data/apps/arffornia/database
  keys:
    - username
    - password
  templates:
    DB_USERNAME: "{% .Secrets.username %}"
    DB_PASSWORD: "{% .Secrets.password %}"
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-server-secret
  namespace: arffornia-server-nexus

spec:
  kubernetes:
    role: arffornia-server-nexus
    authPath: kubernetes 
    
  path: secret/data/apps/arffornia/server
  keys:
    - RCON_PASSWORD
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-server-nexus

spec:
  kubernetes:
    role: arffornia-server-nexus
    authPath: kubernetes 

  path: secret/data/apps/arffornia/proxy
  keys:
    - FORWARDING_SECRET
  type: Opaque

