apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - certificate.yaml
  - secret.yaml
  - realm-export.yaml

helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    version: "24.7.4"
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml