apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-envoy-oidc
  namespace: keycloak
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: adminer
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: longhorn-system
  to:
    - group: ""
      kind: Service
      name: keycloakx-http
