apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smb-storageclass.yaml
  
helmCharts:
  - name: csi-driver-smb
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    version: v1.18.0
    releaseName: csi-driver-smb
    namespace: kube-system
    valuesFile: values.yaml


