apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - service.yaml
  - postgres-cluster.yaml
  - postgres-pv.yaml
  - postgres-pvc.yaml
  - local-storage.yaml