apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgres-s3-credentials
  namespace: postgres
spec:
  path: kvv2/garage-s3/postgres-backup-key
  vaultRole: postgres-role
  keys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  type: Opaque
