apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgres-cluster
  type: ClusterIP 
