apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls
  dnsNames:
    - n8n.arffornia.com
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
    group: cert-manager.io