# Doc: https://github.com/minio/minio/blob/master/helm/minio/values.yaml

mode: standalone 

replicas: 1 

pools: 1
drivesPerNode: 1

existingSecret: "minio-credentials" 


persistence:
  enabled: true
  existingClaim: "minio-nas-pvc" 
  accessMode: ReadWriteMany 
  size: 300Gi 

service:
  type: ClusterIP
  port: "9000"

consoleService:
  type: ClusterIP 
  port: "9001"

ingress:
  enabled: false
consoleIngress:
  enabled: false

buckets:
  - name: longhorn
    policy: none
    purge: false
  - name: postgres-backups
    policy: none
    purge: false

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1"

securityContext:
  enabled: true
  runAsUser: 33  
  runAsGroup: 33  
  fsGroup: 33

ingress:
  enabled: false
  
consoleIngress:
  enabled: true 
  ingressClassName: "public" 
  hosts:
    - s3.arffornia.com 
  tls:
    - secretName: minio-s3-tls 
      hosts:
        - s3.arffornia.com
  annotations:
    cert-manager.io/cluster-issuer: "default-issuer"