apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: gateway-infra
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.1.84
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: gateway-infra
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: gateway-infra
spec:
  gatewayClassName: eg
  listeners:
    - name: http-wildcard
      protocol: HTTP
      port: 80
      hostname: "*.arffornia.com"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              prod-gateway-access: "true"
    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "*.arffornia.com"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: arffornia-wildcard-tls
            namespace: gateway-infra
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              prod-gateway-access: "true"
