apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-proxy-velocity

resources:
  - namespace.yaml
  - secret.yaml
  - config.yaml
  - service-account.yaml

helmCharts:
  - name: minecraft-proxy
    repo: oci://ghcr.io/itzg/minecraft-server-charts
    version: 3.9.0
    releaseName: arffornia-proxy-velocity
    namespace: arffornia-proxy-velocity
    valuesFile: values.yaml
