apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-proxy-velocity

resources:
  - namespace.yaml
  - secret.yaml
  - config.yaml

helmCharts:
  - name: minecraft-proxy
    repo: oci://ghcr.io/arffornia
    version: 3.9.1
    releaseName: arffornia-proxy-velocity
    namespace: arffornia-proxy-velocity
    valuesFile: values.yaml
