apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-proxy-velocity
spec:
  path: secret/arffornia/proxy
  keys:
    - VELOCITY_FORWARDING_SECRET
  type: Opaque
