apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-proxy-velocity
spec:
  path: secret/arffornia/proxy
  keys:
    - CFG_FORWARDING_SECRET
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: luckperms-db-secret
  namespace: arffornia-proxy-velocity

spec:
  path: secret/postgres/luckperms
  keys:
    - username
    - password
  templates:
    CFG_LUCKPERMS_USER: "{% .Secrets.username %}"
    CFG_LUCKPERMS_PASS: "{% .Secrets.password %}"
  type: Opaque
