apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-proxy-velocity
spec:
  kubernetes:
    role: arffornia-proxy-velocity
    authPath: kubernetes
    
  path: secret/data/apps/arffornia/proxy

  keys:
    - FORWARDING_SECRET
  type: Opaque
