apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-proxy-secret
spec:
  path: secret/arffornia/proxy
  keys:
    - FORWARDING_SECRET
  type: Opaque
