apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-proxy-secret
  namespace: arffornia-proxy-secret
spec:
  path: secret/arffornia/proxy
  keys:
    - FORWARDING_SECRET
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: luckperms-db-secret
  # No Namespace (neutral base)

spec:
  path: secret/postgres/luckperms
  keys:
    - username
    - password
  templates:
    LUCKPERMS_USER: "{% .Secrets.username %}"
    LUCKPERMS_PASS: "{% .Secrets.password %}"
  type: Opaque
