apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-db-secret
  namespace: arffornia-proxy-velocity
spec:
  path: secret/postgres/arffornia
  keys:
    - username
    - password
  templates:
    DB_USERNAME: "{% .Secrets.username %}"
    DB_PASSWORD: "{% .Secrets.password %}"
  type: Opaque
