apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - certificate.yaml
  - secret.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "75.15.2" 
    releaseName: monitoring-stack
    namespace: monitoring
    valuesFile: values.yaml