apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd-server-certificate.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.13.2
  - ingress.yaml
  - apps.yaml

patches:
  - path: argocd-cm.yaml