---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: "role:denied"
  scopes: "[groups]"
  policy.csv: |
    g, infra, role:admin
    g, member, role:readonly
