apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  namespace: argocd
spec:
  path: kvv2/argocd/oidc
  type: Opaque
  reconcileStrategy: Merge
  keys:
    - oidc.keycloak.clientSecret
