apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arffornia-proxy-velocity
  namespace: argocd
  labels:
    app: arffornia-proxy-velocity
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/TheGostsniperfr/infra.git
    targetRevision: HEAD
    path: k8s/config/arffornia/proxy
  destination:
    name: in-cluster
    namespace: arffornia-proxy-velocity
