apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - nextcloud-certificate.yaml
  - secret.yaml
  
helmCharts:
  - name: nextcloud
    repo: https://helm.releases.hashicorp.com
    version: 6.6.4
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: nextcloud-values.yaml


