apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - secret.yaml
  - nas-pvc.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 9.1.3
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: nextcloud-values.yaml

  - name: secure-route
    releaseName: nextcloud-routes
    namespace: nextcloud
    valuesFile: values-secure-route.yaml
