apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - nextcloud-certificate.yaml
  - secret.yaml
  - nas-pvc.yaml
  
helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 6.6.6
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: nextcloud-values.yaml


