# Values: https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

replicaCount: 1

image:
  repository: nextcloud
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/proxy-body-size: "200G"
  className: public
  hosts:
    - host: nextcloud.arffornia.com
      paths:
        - /
  tls:
    - hosts:
        - nextcloud.arffornia.com
      secretName: nextcloud-tls

service:
  type: ClusterIP

nextcloud:
  host: nextcloud.arffornia.com
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  database:
    type: postgresql
    host: postgres-cluster.postgres.svc.cluster.local
    database: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-db-secret
      usernameKey: username
      passwordKey: password

  extraVolumes:
    - name: nextcloud-nas-data
      persistentVolumeClaim:
        claimName: nextcloud-nas-pvc

  extraVolumeMounts:
    - name: nextcloud-nas-data
      mountPath: /mnt/nas

redis:
  enabled: true

extraEnv:
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "nextcloud.arffornia.com"

  - name: NEXTCLOUD_INSTALL_APPS
    value: "files_external" # comma separated

phpClientHttpsFix:
  enabled: true
  protocol: https

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-sa
  