# Values: https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

replicaCount: 1

image:
  repository: nextcloud
  tag: latest
  pullPolicy: IfNotPresent

extraVolumes:
  - name: nextcloud-nas-data
    persistentVolumeClaim:
      claimName: nextcloud-nas-pvc

extraVolumeMounts:
  - name: nextcloud-nas-data
    mountPath: /mnt/nas

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    kubernetes.io/ingress.class: public
  className: public
  hosts:
    - host: nextcloud.arffornia.com
      paths:
        - /
  tls:
    - hosts:
        - nextcloud.arffornia.com
      secretName: nextcloud-tls

service:
  type: ClusterIP

nextcloud:
  host: nextcloud.arffornia.com
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  database:
    type: postgresql
    host: postgres-cluster.postgres.svc.cluster.local
    database: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-db-secret
      usernameKey: username
      passwordKey: password

redis:
  enabled: true

extraEnv:
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "nextcloud.arffornia.com"

phpClientHttpsFix:
  enabled: true
  protocol: https
  