# Values: https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

image:
  repository: nextcloud
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: default-issuer
  ingressClassName: public
  hosts:
    - host: nextcloud.arffornia.com
  tls:
    - hosts:
        - nextcloud.arffornia.com
      secretName: nextcloud-tls

nextcloud:
  host: nextcloud.arffornia.com
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  database:
    type: postgresql
    host: postgres-cluster.postgres.svc.cluster.local
    database: nextcloud
    existingSecret:
      enabled: true
      secretName: nextcloud-db-secret
      usernameKey: username
      passwordKey: password

extraEnv:
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "nextcloud.arffornia.com"
