apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls 
  dnsNames:
    - vaultwarden.arffornia.com
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
    group: cert-manager.io
