apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluemap-web
  namespace: arffornia-bluemap-web
  labels:
    app: bluemap-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluemap-web
  template:
    metadata:
      labels:
        app: bluemap-web
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 3000
      containers:
        - name: nginx
          image: nginx:1.27.0-alpine
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: bluemap-data
              mountPath: /data/bluemap-web
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: bluemap-data
          persistentVolumeClaim:
            claimName: arffornia-bluemap-pvc
        - name: nginx-config
          configMap:
            name: bluemap-nginx-config
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}