apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arffornia-bluemap-web
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml