{{- range $routeName, $routeConfig := .Values.routes }}
{{- if and $routeConfig.auth.enabled $routeConfig.auth.vault }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "{{ $routeName }}-envoy-auth-secret"
  namespace: "{{ $.Release.Namespace }}"
spec:
  path: {{ $routeConfig.auth.vault.path | quote }}
  vaultRole: {{ $routeConfig.auth.vault.role | quote }}
  keys:
    - client-secret
  type: Opaque
---
{{- end }}
{{- end }}
