apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  labels:
    app: ollama
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/TheGostsniperfr/infra.git
    targetRevision: HEAD
    path: k8s/config/ollama
  destination:
    name: in-cluster
    namespace: ollama