apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    app: postgres
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/TheGostsniperfr/infra.git
    targetRevision: HEAD
    path: k8s/config/postgres
  destination:
    name: in-cluster
    namespace: postgres
