apiVersion: v1
kind: ConfigMap
metadata:
  name: arffornia-website-config
  namespace: arffornia-website
data:
  APP_NAME: "Arffornia Website"
  APP_ENV: "local"
  # APP_KEY:
  APP_DEBUG: "true"
  APP_TIMEZONE: "UTC"
  APP_URL: "https://arffornia.com"

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-cluster.postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "arffornia"
  # DB_USERNAME:
  # DB_PASSWORD:

  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "pusher"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  CACHE_PREFIX: ""

  MEMCACHED_HOST: "127.0.0.1"

  VITE_APP_NAME: "${APP_NAME}"

  # AZURE_OAUTH_CLIENT_ID:
  # AZURE_OAUTH_CLIENT_SECRET:
  AZURE_OAUTH_REDIRECT_URI: "https://arffornia.com/login"

  # PUSHER_APP_ID:
  # PUSHER_APP_KEY:
  # PUSHER_APP_SECRET:
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: "https"
  PUSHER_APP_CLUSTER: "eu"

  # REVERB_APP_ID: 
  # REVERB_APP_KEY:
  # REVERB_APP_SECRET:
  REVERB_HOST: "https://arffornia.com"
  REVERB_PORT: "443"
  REVERB_SCHEME: "https"

  # VITE_REVERB_APP_KEY: "${REVERB_APP_KEY}"
  VITE_REVERB_HOST: "https://arffornia.com"
  VITE_REVERB_PORT: "443"
  VITE_REVERB_SCHEME: "https"
