apiVersion: apps/v1
kind: Deployment
metadata:
  name: arffornia-website
  namespace: arffornia-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arffornia-website
  template:
    metadata:
      labels:
        app: arffornia-website
    spec:
      containers:
      - name: fpm
        image: ghcr.io/arffornia/arffornia_website:latest
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: arffornia-website-secret
        - secretRef:
            name: arffornia-website-secret-template
        - secretRef:
            name: arffornia-db-secret
        - configMapRef:
            name: arffornia-website-config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"

      - name: nginx
        image: ghcr.io/arffornia/nginx_arffornia_website:latest
        ports:
          - containerPort: 80
        env:
          - name: TARGET_HOST
            value: "127.0.0.1"
          - name: TARGET_PORT
            value: "9000"
          - name: LISTEN_PORT
            value: "80"
