apiVersion: apps/v1
kind: Deployment
metadata:
  name: arffornia-website
  namespace: arffornia-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arffornia-website
  template:
    metadata:
      labels:
        app: arffornia-website
    spec:
      containers:
      - name: app
        image: ghcr.io/arffornia/arffornia_website:latest
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: arffornia-website-secret
        - secretRef:
            name: arffornia-db-secret
        - configMapRef:
            name: arffornia-website-config
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
