apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-website

resources:
  - namespace.yaml
  - secret.yaml
  - certificate.yaml
  - config.yaml

helmCharts:
  - name: arffornia-website-chart
    repo: oci://ghcr.io/arffornia
    version: latest # Just for test period
    releaseName: arffornia-website
    namespace: arffornia-website
    valuesFile: values.yaml

