apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arffornia-website

resources:
  - namespace.yaml
  - ingress.yaml
  - deployment.yaml
  - secret.yaml
  - certificate.yaml
  - config.yaml
