apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-db-secret
  namespace: arffornia-website
spec:
  path: secret/postgres/arffornia
  keys:
    - username
    - password
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - username
    - password
  type: Opaque
