apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - APP_KEY

    - DB_USERNAME
    - DB_PASSWORD

    - AZURE_OAUTH_CLIENT_ID
    - AZURE_OAUTH_CLIENT_SECRET

    - PUSHER_APP_ID
    - PUSHER_APP_KEY
    - PUSHER_APP_SECRET

    - REVERB_APP_ID
    - REVERB_APP_KEY
    - REVERB_APP_SECRET

    - VITE_REVERB_APP_KEY # "${REVERB_APP_KEY}"
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-registry
  namespace: arffornia-website
spec:
  path: secret/docker-registry
  type: kubernetes.io/dockerconfigjson
