apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - APP_KEY

    - DB_PASSWORD

    - AZURE_OAUTH_CLIENT_ID
    - AZURE_OAUTH_CLIENT_SECRET

    - PUSHER_APP_ID
    - PUSHER_APP_KEY
    - PUSHER_APP_SECRET

    - REVERB_APP_ID
    - REVERB_APP_KEY
    - REVERB_APP_SECRET
  type: Opaque

---
# Template disable default secret generation
# See: https://github.com/ricoberger/vault-secrets-operator#using-templated-secrets

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - REVERB_APP_KEY
  templates: 
    VITE_REVERB_APP_KEY: "{% .Secrets.REVERB_APP_KEY %}"
  type: Opaque

---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-db-secret
  namespace: arffornia-website
spec:
  path: secret/postgres/arffornia
  keys:
    - username
    - password
  templates:
    DB_USERNAME: "{% .Secrets.username %}"
    DB_PASSWORD: "{% .Secrets.password %}"
  type: Opaque

