apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - APP_KEY

    - DB_PASSWORD

    - AZURE_OAUTH_CLIENT_ID
    - AZURE_OAUTH_CLIENT_SECRET

    - PUSHER_APP_ID
    - PUSHER_APP_KEY
    - PUSHER_APP_SECRET

    - REVERB_APP_ID
    - REVERB_APP_KEY
    - REVERB_APP_SECRET
  type: Opaque

---
# Template disable default secret generation
# See: https://github.com/ricoberger/vault-secrets-operator#using-templated-secrets

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-website-secret-template
  namespace: arffornia-website
spec:
  path: secret/arffornia/website
  keys:
    - REVERB_APP_KEY
  templates: 
    VITE_REVERB_APP_KEY: "{% .Secrets.REVERB_APP_KEY %}"
  type: Opaque

---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-db-secret
  namespace: arffornia-website
spec:
  path: secret/postgres/arffornia
  keys:
    - username
    - password
  templates:
    DB_USERNAME: "{% .Secrets.username %}"
    DB_PASSWORD: "{% .Secrets.password %}"
  type: Opaque
---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-svc-proxy-secret
  namespace: arffornia-website
spec:
  path: secret/arffornia/svc-proxy
  keys:
    - SVC_ID
    - SVC_PASSWORD
  templates:
    SVC_ACCOUNT_PROXY_NAME: "Minecraft Proxy Link"
    SVC_ACCOUNT_PROXY_ROLES: "nuvotifier_service"
    SVC_ACCOUNT_PROXY_CLIENT_ID: "{% .Secrets.SVC_ID %}"
    SVC_ACCOUNT_PROXY_CLIENT_SECRET: "{% .Secrets.SVC_PASSWORD %}"
  type: Opaque
---

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: arffornia-svc-secret
  namespace: arffornia-website

spec:
  path: secret/arffornia/svc
  keys:
    - SVC_ID
    - SVC_PASSWORD
  templates:
    SVC_ACCOUNT_MINECRAFT_NAME: "Minecraft Server Link"
    SVC_ACCOUNT_MINECRAFT_ROLES: "progression_editor,user_editor,team_editor"
    SVC_ACCOUNT_MINECRAFT_CLIENT_ID: "{% .Secrets.SVC_ID %}"
    SVC_ACCOUNT_MINECRAFT_CLIENT_SECRET: "{% .Secrets.SVC_PASSWORD %}"
  type: Opaque
