apiVersion: v1
kind: Service
metadata:
  name: arffornia-website
  namespace: arffornia-website
spec:
  selector:
    app: arffornia-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP