apiVersion: v1
kind: Service
metadata:
  name: arffornia-website
  namespace: arffornia-website
spec:
  selector:
    app: arffornia-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort:
    - name: php-fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP