routes:
  vault:
    hostnames:
      - "arffornia.com"
    rules:
      - backendRefs:
          - name: arffornia-website-chart
            port: 80
    auth:
      enabled: false
    ipFilter:
      enabled: false
